<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'Access denied.' => 'Erişim engellendi.',
    'Add' => 'Ekle',
    'Add child' => 'Alt alan ekle',
    'Add {type}' => '{type} ekle',
    'Ancestors' => 'Atalar',
    'Are you sure you want to delete this item?' => 'Bu öğeyi silmek istediğinize emin misiniz?',
    'Assign' => 'Ata',
    'Assign permission' => 'İzin atama',
    'Assigned items' => 'Atanan öğeler',
    'Assignments' => 'Atamalar',
    'Business rule' => 'İş kuralı',
    'Cancel' => 'İptal',
    'Create' => 'Oluştur',
    'Delete' => 'Sil',
    'Data' => 'Bilgi',
    'Descendants' => 'Torunlar',
    'Description' => 'Tanımlama',
    'Edit' => 'Düzenle',
    'Invalid request.' => 'Geçersiz istek',
    'Item does not exist.' => 'Öğe yok.',
    'Items' => 'Öğeler',
    'Items assigned to this user' => 'Bu kullanıcıya atanan öğeler',
    'New {type}' => 'Yeni {type}',
    'No assignments found.' => 'Atama bulunamadı.',
    'No {type} found.' => '{type} bulunamadı.',
    'Page not found.' => 'Sayfa bulunamadı.',
    'Permissions' => 'İzinler',
    'Permissions granted by this item' => 'Bu öğe ile verilen izinler',
    'Permissions that inherit this item' => 'Bu öğeden miras alınan izinler',
    'Remove' => 'Kaldır',
    'Revoke' => 'Geri al',
    'Save' => 'Kaydet',
    'Select item' => 'Öğe seç',
    'System name' => 'Sistem ismi',
    'System name cannot be changed after creation.' => 'Oluşturulduktan sonra sistem adı değiştirilemez.',
    'This item does not have any ancestors.' => 'Öğenin herhangi bir atası bulunmuyor.',
    'This item does not have any descendants.' => 'Öğenin herhangi bir torunu bulunmuyor.',
    'This user does not have any assignments.' => 'Bu kullanıcıya ait herhangi bir atama yok.',
    'Type' => 'Tip',
    'User' => 'Kullanıcı',
    'View' => 'Görüntüle',
    'operation|operations' => 'işlem|işlemler',
    'role|roles' => 'rol|roller',
    'task|tasks' => 'görev|görevler',
);
